import { GetStaticProps, NextPage } from 'next';
import Layout from '../../components/layout';
import { getPosts } from '../../lib/posts';
import Head from 'next/head';
import utilStyles from '../../styles/utils.module.css';
import Link from 'next/link';

const siteTitle = 'List Post';

// define props that will be available
type ListPostProps = {
  allPostsData: any[];
};

/**
 * add generic on type NextPage if page has props.
 * props are generated by "getStaticProps" function below
 */
const ListPost: NextPage<ListPostProps> = ({ allPostsData }) => {
  // const ListPost = ({ allPostsData }: { allPostsData: any[] }) => {
  return (
    <Layout>
      <Head>
        <title>{siteTitle}</title>
      </Head>
      <h2 className={utilStyles.headingLg}>Blog</h2>
      <ul className={utilStyles.list}>
        <li className={utilStyles.listItem} key={0}>
          <Link href="/posts/default-post">
            <a>Default Post</a>
          </Link>
        </li>
        {allPostsData.map(({ id, title, slug }) => (
          <li className={utilStyles.listItem} key={id}>
            <Link href={`/posts/${slug}`}>
              <a>{title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </Layout>
  );
};

export default ListPost;

/**
 * GetStaticProps is used for fetching data on server side before pre-render the page.
 * in production, it runs at build time.
 * in development, it runs on every request.
 * it must be exported and it can only be exported from a page.
 * read about the 'context' parameter here:
 * https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation
 */
export const getStaticProps: GetStaticProps = async (context) => {
  const allPostsData = getPosts();
  console.log('xxxxxxx');

  return {
    props: {
      allPostsData,
    },
  };
};
